### PR TITLE
Non rigid block reg

### PR DESCRIPTION
**Pull request by xigumalu**
I adapted the non-rigid (block) registration, so that it can be used in addition to aligning movies across planes (in z-direction).
Most importantly, I changed (in blockReg2P) the way x- and y-range is determined. Instead of using xyValid (which crops the field of view across all planes), the block shifts (ops1{k}.DS) are used for each plane separately to determine x- and y-range. This will also affect non-rigid registrations that do not use alignment across planes. I think this is a better way, but please check.

### CODE REVIEW

**Comment by marius10p** [comment]
@carsen-stringer , please check that @xigumalu's version is consistent with your non-rigid alignment algorithm.

**Comment by xigumalu** [comment]
Hi,
can you please check and merge if everything is fine?

**Comment by carsen-stringer** [comment]
cool thanks!

**Comment by carsen-stringer** [comment]
I have made some changes to reg2P.m. I merged reg2P.m and blockReg2P.m so that we don't have to worry about changing both files anymore. Also, now you can get the mean red image at the same time as registration if you choose. Please check though that I didn't break your alignment scripts. Thanks!

**Pull request merged**
